DniproFuture/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DniproFuture.Models;

namespace DniproFuture.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        DniproFutureModelRepository _repository = new DniproFutureModelRepository();

        // GET: News
        public ActionResult Index()
        {
            return View(_repository.GetListOfNews());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = _repository.FindInNewsById(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            ViewBag.Languages = _repository.GetLanguagesList();
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NewsInputModel news, HttpPostedFileBase[] images)
        {
            if (ModelState.IsValid)
            {
                List<string> photosList = new List<string>();
                foreach (HttpPostedFileBase photo in images)
                {
                    if (photo != null)
                    {
                        string filename = Path.GetRandomFileName().Split(new[] { '.' }, StringSplitOptions.RemoveEmptyEntries)[0] + "." + photo.FileName.Split(new[] { '.' }, StringSplitOptions.RemoveEmptyEntries)[1];
                        var path = Path.Combine(Server.MapPath("~/Content/img/News"), filename);
                        photo.SaveAs(path);
                        photosList.Add(filename);

                    }
                }

                news.NewsInfo.Images = String.Join(";", photosList);

                _repository.AddNews(news);
                return RedirectToAction("Index");
            }

            ViewBag.Languages = _repository.GetLanguagesList();
            return View(news);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = _repository.FindInNewsById(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Images,Date")] News news)
        {
            if (ModelState.IsValid)
            {
                _repository.EditNews(news);
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = _repository.FindInNewsById(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _repository.RemoveNewsById(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DniproFuture/Views/Shared/AdminNavbar.cshtml
<!-- Navigation -->
<nav class="navbar navbar-default navbar-shrink navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="backFlag">
                <a class="page-scroll" href="/#page-top"><img class="logo navbar-brand" src="@Url.Content("~/Content/img/logo.png")" /></a>
            </div>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="@Url.Action("Index", "Admin")">Админка</a>
                </li>
                <li>
                    <a class="page-scroll" href="@Url.Action("Index", "Mails")">
                        Почта
                        <div type="button" id="unread" class="btn btn-danger btn-xs" hidden="hidden"></div>
                    </a>
                </li>
                <li>
                    <a class="page-scroll" href="@Url.Action("Index", "News")">Новости</a>
                </li>
                <li>
                    <a class="page-scroll" href="@Url.Action("Index", "NeedHelps")">Кому помочь</a>
                </li>
                <li>
                    <a class="page-scroll" href="@Url.Action("Index", "Partners")">Партнеры</a>
                </li>
                <li>
                    <a class="page-scroll" href="@Url.Action("Index", "Projects")">Проекты</a>
                </li>
            </ul>
        </div>
        <div id="languages">
            <a href="@Url.Action("ChangeCulture",new { lang = "uk", returnUrl = this.Request.RawUrl })">
                <img src="@Url.Content("~/Content/img/blank.gif")" class="flag flag-ua" alt="Українська" />
            </a><br />
            <a href="@Url.Action("ChangeCulture",new { lang = "ru", returnUrl = this.Request.RawUrl })">
                <img src="@Url.Content("~/Content/img/blank.gif")" class="flag flag-ru" alt="Русский" />
            </a><br />
            <a href="@Url.Action("ChangeCulture",new { lang = "en", returnUrl = this.Request.RawUrl })">
                <img src="@Url.Content("~/Content/img/blank.gif")" class="flag flag-us" alt="English" />
            </a>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

DniproFuture/Views/Shared/CustomNavbar.cshtml
<!-- Navigation -->
<nav class="navbar navbar-default navbar-shrink navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="backFlag">
                <a class="page-scroll" href="/#page-top"><img class="logo navbar-brand" src="@Url.Content("~/Content/img/logo.png")" /></a>
            </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="/#helpNow">@ViewRes._HomeStrings.NavBarHelpNow</a>
                </li>
                <li>
                    <a class="page-scroll" href="/#donation">@ViewRes._HomeStrings.NavBarDonation</a>
                </li>
                <li>
                    <a class="page-scroll" href="/#about">@ViewRes._HomeStrings.NavBarAbout</a>
                </li>
                <li>
                    <a class="page-scroll" href="/#news">@ViewRes._HomeStrings.NavBarNews</a>
                </li>
                <li>
                    <a class="page-scroll" href="/#how">@ViewRes._HomeStrings.NavBarHow</a>
                </li>
                <li>
                    <a class="page-scroll" href="/#partners">@ViewRes._HomeStrings.NavBarPartners</a>
                </li>
                <li>
                    <a class="page-scroll" href="/#clients">@ViewRes._HomeStrings.NavBarClients</a>
                </li>
                <li>
                    <a class="page-scroll" href="/#contacts">@ViewRes._HomeStrings.NavBarContacts</a>
                </li>
            </ul>
        </div>
        <div id="languages">
            <a href="@Url.Action("ChangeCulture",new { lang = "uk", returnUrl = this.Request.RawUrl })">
                <img src="@Url.Content("~/Content/img/blank.gif")" class="flag flag-ua" alt="Українська" />
            </a><br/>
            <a href="@Url.Action("ChangeCulture",new { lang = "ru", returnUrl = this.Request.RawUrl })">
                <img src="@Url.Content("~/Content/img/blank.gif")" class="flag flag-ru" alt="Русский" />
            </a><br />
            <a href="@Url.Action("ChangeCulture",new { lang = "en", returnUrl = this.Request.RawUrl })">
                <img src="@Url.Content("~/Content/img/blank.gif")" class="flag flag-us" alt="English" />
            </a>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

DniproFuture/Views/Shared/_AdminLayout.cshtml
@{
    ViewBag.Title = "_AdminLayout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 @{
        Html.RenderPartial("AdminNavbar");
    }


    @RenderBody()

@section scripts{
    @Styles.Render("~/Content/customBootstrap")
    @Scripts.Render("~/bundles/admin")
}

DniproFuture/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewRes._LayoutStrings.LayoutTitle</title>

    <!-- Custom Fonts -->
    <link href="~/Content/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Andika&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="page-top" class="index">

    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    @Scripts.Render("~/bundles/agency")

    @Scripts.Render("~/bundles/jqueryval")

    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/flags")
    @RenderSection("scripts", false)

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h4>@ViewRes._LayoutStrings.FooterContacts</h4>
                    <div class="text-left col-md-4">
                        <ul class="list-unstyled">
                            <li>
                                Tel:
                            </li>
                            <li>
                                E-mail:
                            </li>
                            <li>
                                Skype:
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <span class="copyright">ВоТаНа &copy; Майбутнє Дніпра 2015</span>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

DniproFuture/Views/Shared/_MainLayout.cshtml
@{
    ViewBag.Title = "_MainLayout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    Html.RenderPartial("NavBar");
}

@RenderBody()

@section scripts{
    @Scripts.Render("~/bundles/animation")
}

DniproFuture/Views/Shared/_OtherLayout.cshtml
@{
    ViewBag.Title = "_OtherLayout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    Html.RenderPartial("CustomNavbar");
}

@RenderBody()

@section scripts{
    @Styles.Render("~/Content/customBootstrap")
}